create extension if not exists pgcrypto;

create table if not exists public.alert_clients (
  id uuid primary key default gen_random_uuid(),
  public_id uuid not null unique default gen_random_uuid(),
  secret_hash text not null,
  email text,
  discord_webhook text,
  telegram_chat_id text,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.price_alerts (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references public.alert_clients(id) on delete cascade,
  app_id bigint not null,
  product_type text not null default 'app' check (product_type in ('app', 'sub')),
  game_name text not null,
  target_amount numeric not null check (target_amount >= 0),
  target_currency text not null check (target_currency ~ '^[A-Z]{3}$'),
  region_code text not null check (region_code ~ '^[a-z]{2}$'),
  enabled boolean not null default true,
  current_amount numeric,
  current_currency text,
  discount_percent integer not null default 0,
  last_checked_at timestamptz,
  last_alerted_at timestamptz,
  last_alerted_price numeric,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (client_id, app_id, product_type, region_code, target_currency)
);

create table if not exists public.alert_events (
  id bigint generated by default as identity primary key,
  alert_id uuid references public.price_alerts(id) on delete set null,
  client_id uuid references public.alert_clients(id) on delete set null,
  channel text not null check (channel in ('email', 'discord', 'telegram')),
  status text not null check (status in ('sent', 'failed')),
  price_amount numeric,
  currency text,
  error_message text,
  created_at timestamptz not null default now()
);

create index if not exists price_alerts_due_idx on public.price_alerts (enabled, last_checked_at);
create index if not exists alert_events_client_created_idx on public.alert_events (client_id, created_at desc);

alter table public.alert_clients enable row level security;
alter table public.price_alerts enable row level security;
alter table public.alert_events enable row level security;

-- Không tạo policy công khai. Backend chỉ truy cập bằng SUPABASE_SERVICE_ROLE_KEY.
