create table if not exists public.user_accounts (
  id uuid primary key default gen_random_uuid(),
  steam_id text not null unique check (steam_id ~ '^[0-9]{17}$'),
  display_name text,
  avatar_url text,
  profile_url text,
  email text,
  discord_webhook text,
  telegram_chat_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_login_at timestamptz not null default now()
);

alter table public.alert_clients add column if not exists user_id uuid references public.user_accounts(id) on delete cascade;
create unique index if not exists alert_clients_user_id_idx on public.alert_clients(user_id) where user_id is not null;

create table if not exists public.cloud_tracker (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.user_accounts(id) on delete cascade,
  app_id bigint not null,
  product_type text not null default 'app' check (product_type in ('app', 'sub')),
  game_data jsonb not null default '{}'::jsonb,
  target_amount numeric,
  target_currency text check (target_currency is null or target_currency ~ '^[A-Z]{3}$'),
  region_code text not null default 'vn' check (region_code ~ '^[a-z]{2}$'),
  last_history_scan_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, app_id, product_type)
);

create table if not exists public.user_wishlist (
  user_id uuid not null references public.user_accounts(id) on delete cascade,
  app_id bigint not null,
  priority integer not null default 0,
  added_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  synced_at timestamptz not null default now(),
  primary key (user_id, app_id)
);

create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.user_accounts(id) on delete cascade,
  endpoint text not null unique,
  subscription jsonb not null,
  user_agent text,
  enabled boolean not null default true,
  last_success_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.price_snapshots (
  id bigint generated by default as identity primary key,
  app_id bigint not null,
  product_type text not null default 'app' check (product_type in ('app', 'sub')),
  region_code text not null check (region_code ~ '^[a-z]{2}$'),
  price_amount numeric not null check (price_amount >= 0),
  original_amount numeric,
  currency text not null check (currency ~ '^[A-Z]{3}$'),
  discount_percent integer not null default 0,
  available boolean not null default true,
  captured_at timestamptz not null default now()
);
create index if not exists price_snapshots_lookup_idx on public.price_snapshots(app_id, product_type, region_code, captured_at desc);
create index if not exists cloud_tracker_history_due_idx on public.cloud_tracker(last_history_scan_at asc nulls first);

create table if not exists public.cron_runs (
  id uuid primary key default gen_random_uuid(),
  job_name text not null,
  status text not null check (status in ('running', 'success', 'failed')),
  checked_count integer not null default 0,
  triggered_count integer not null default 0,
  sent_count integer not null default 0,
  failed_count integer not null default 0,
  details jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create table if not exists public.retry_jobs (
  id bigint generated by default as identity primary key,
  job_type text not null,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending', 'processing', 'done', 'failed')),
  attempts integer not null default 0,
  next_attempt_at timestamptz not null default now(),
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists retry_jobs_due_idx on public.retry_jobs(status, next_attempt_at);

create table if not exists public.service_health (
  service text primary key,
  status text not null check (status in ('operational', 'degraded', 'down')),
  latency_ms integer,
  message text,
  checked_at timestamptz not null default now()
);

alter table public.alert_events drop constraint if exists alert_events_channel_check;
alter table public.alert_events add constraint alert_events_channel_check check (channel in ('email', 'discord', 'telegram', 'webpush'));

alter table public.user_accounts enable row level security;
alter table public.cloud_tracker enable row level security;
alter table public.user_wishlist enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.price_snapshots enable row level security;
alter table public.cron_runs enable row level security;
alter table public.retry_jobs enable row level security;
alter table public.service_health enable row level security;

-- No public policies: only the backend service-role key may access cloud data.
